import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./header";

const inter = Inter({ subsets: ["latin"] });
// const myFont = localFont({ src: "./fonts/Poppins-Regular.ttf" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <Header></Header>
        <div>{children}</div>
      </body>
    </html>
  );
}
